sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '0.12'
  - v4
  - stable
after_success:
  - 'travis-after-all && npm run semantic-release'
env:
  global:
    - secure: fzIbdfeyZZqjrJnwSMRMOingFNc3OdP/t9svYbjsq4TJO0iLTLGD22AhgmYl1DwOgCRPBDyGIzXltYOZr1bj295Ogp0DmI2hWhCLIHblcUrV72vRmK1a0sXI61hAqgXJ03o6XJQUCDHY3TcJd6DOKz6QxLtkJti8kMTREWDrYZykdHZUXU7EidSystcQvRP5tcOaXTQTynlzKDuhSWF9Kyxsb0G7HM+EfEytZXhO0hdsjq33JjS+dwKmrZ183ZiCM3h7Ib0fTz4ID3oHADc/wurXQl8S6ONSq60K84TlkyXLIsSKD5o7wIqevbCMiOVDOKBcWUr9Z9mHi8H6nNkovRX3DbGLerC2xp8eRLp9RYXUUjSTRBueF3cPTDyLXN0ZIc4QntIGOmPZnz8lI1l8iVpWz6ST+d1c4OyChyGDwSjbj0SGVdh9Tr3LQqTIooxGvgD9GU14Y9gHzvvwlorIcqzfzHKS9mnMp5V86smCuySDZ1BqqecwXI/0m6pNceBP0H44iFTEkVLBGI6DePO0si351xErM3fZLdJblrUdIQCdDVt/aX3Qc+wssyrvZMZAm+NBknQ5irtVlYAxYG5XhsNqlccZrKpazJAaZXlgdu47kJ+4suhKtcrsVG24/LPzBeHjXCyv9fUgrDyYbqG+dOcoO2Q6afyGxbxjw/rk8Kg=
    - secure: E23BJML7apLVPVTFS9YhmMOIZ+cfT67YzS8yex3r+0OJ5kW+mmgsidEs/q2xOrPxdZ9RcNLyDwBSaik5imKBTPJV9VoC8v1FJ02f5BojSBigRDYFWMr6Uyo1vLW6vwoxDkWQT7rMywTr9NmsqaEVXmF/yxiANHm5G1jZEpcgZtvqAH9bqQhollqFg2zJWgOZLo1Dra4yRkOy6StLtn9V6c51QjqKHdotR59EnCGmIIiDZ1JBr8DiEvJWi92k4Y9KbVJ2jswdcsrIRNB+LsoQrfAB+ER9O0FOxWWOpw7Oh8QUULt3eDl83erLW3XPCmBCx9mWddb++oUbwXyfWKZPAT5caTqrnA305zwt94Q0cWay8EUREKugsGgHifaL7PLA20Fhsmgo89oZpp+F8JW0juCCd7/oK1FIye3YobMETezjWvYrDxr0FoXhJHYNE+putGSttMtfoGxpliwtvJmOWzF7qWlx8tLxQAwkNwwKxbvnuy4hvNDTvJ1W3OP0ifVY8nxJYdUFrQfadNvqsu9isnSaxqYPwB20AAAPV/ZJEmL1kP3YWep9y7BPerupW9PVAg2y8eMtrpXqAZKIrO5Ftwy5jRhpMkO0S1V+UvCXLuFQISlLSiO6+sqDu6bazYa2iVm1mzsF16uitR0dBIbiQQec63jTzLqAwbWULGWS2ts=
